### ISSUE TITLE
Weights for mmd loss？ 

### ISSUE THREAD

**Issue by LiDaiY** [paul007pl/PointAtrousGraph#1]
Hi, thank you for your code. I'm interested in the MMD loss. Can you give me some advice about the weight of MMD_loss if I want to add it to my own sem_seg network?
https://github.com/paul007pl/PointAtrousGraph/blob/f45b189f9f4f6a25c1a3b85e58736dcc8b976371/sem_seg/train_ss.py#L39

**Comment by paul007pl** [comment]
> Hi, thank you for your code. I'm interested in the MMD loss. Can you give me some advice about the weight of MMD_loss if I want to add it to my own sem_seg network?
> https://github.com/paul007pl/PointAtrousGraph/blob/f45b189f9f4f6a25c1a3b85e58736dcc8b976371/sem_seg/train_ss.py#L39

Hi, thanks for your interest. As for the weights of MMD loss, it is not easy for me to guide you for your own network.  I can only suggest you to try a few different weights. During training, make sure the auxiliary loss won't influence your main loss functions, since the purpose of it is to make your feature embeddings more informative.

Maybe the following link can help:
https://ermongroup.github.io/blog/a-tutorial-on-mmd-variational-autoencoders/
